services:
    nginx:
        platform: linux/arm64
        image: arm64v8/nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php
        networks:
            - app-network

    php:
        platform: linux/arm64
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        networks:
            - app-network

    mysql:
        platform: linux/amd64
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            --default_authentication_plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

    phpmyadmin:
        platform: linux/arm64
        image: arm64v8/phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80
        networks:
            - app-network

    mailhog:
        platform: linux/amd64
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge